name: Sync Labels
on:
  workflow_dispatch:
  push:
    paths:
      - labels.json
    branches:
      - main

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2.3.4

      - name: Composer Install
        run: composer install

      - name: Run Label Tool
        run: php label.php
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}